# Generated by Django 5.2.1 on 2025-09-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Dispute', 'Dispute')], default='Pending', max_length=20),
        ),
    ]
