# Generated by Django 5.2.1 on 2025-09-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='admin_notified',
            field=models.BooleanField(default=False),
        ),
    ]
