# Generated by Django 5.2.1 on 2025-09-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customerprofile_address_customerprofile_latitude_and_more'),
        ('payments', '0006_alter_transaction_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile'),
        ),
    ]
