# Generated by Django 5.2.1 on 2025-09-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_transaction_status_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pay', 'Pay Now'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=10),
        ),
    ]
