# Generated by Django 5.2.1 on 2025-09-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_transaction_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pay', 'Pay Now'), ('Waiting', 'Waiting Farmer Confirmation'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=10),
        ),
    ]
