# Generated by Django 4.2.24 on 2025-09-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_farmer'),
        ('accounts', '0034_alter_farmerreview_customer_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='bid_amount',
        ),
        migrations.RemoveField(
            model_name='message',
            name='bid_quantity',
        ),
        migrations.RemoveField(
            model_name='message',
            name='bid_status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_bid',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='farmer_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='farmer_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_chats', to='accounts.customerprofile'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_chats', to='accounts.farmerprofile'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('farmer', 'customer')},
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
