# Generated by Django 5.2.1 on 2025-08-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='product',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='farmer_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
