# Generated by Django 5.2.1 on 2025-09-12 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_farmerreview_customer_and_more'),
        ('chat', '0001_initial'),
        ('products', '0016_alter_product_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='bid_amount',
        ),
        migrations.RemoveField(
            model_name='message',
            name='bid_quantity',
        ),
        migrations.RemoveField(
            model_name='message',
            name='bid_status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_bid',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='farmer_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='farmer_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_chats', to='accounts.customerprofile'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_chats', to='accounts.farmerprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
