# Generated by Django 5.2.1 on 2025-08-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_product_chatroom_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='products',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='message',
            name='bid_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True),
        ),
    ]
