# Generated by Django 5.2.1 on 2025-09-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_product_remove_message_bid_amount_and_more'),
    ]

    operations = [
    ]
