# Generated by Django 5.2.1 on 2025-08-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_products_chatroom_product_and_more'),
        ('products', '0004_product_sub_category_roman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
