# Generated by Django 5.2.1 on 2025-09-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_farmerreview_customer_and_more'),
        ('chat', '0003_auto_20250910_2213'),
        ('products', '0016_alter_product_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('product', 'farmer', 'customer')},
        ),
    ]
