# Generated by Django 5.2.1 on 2025-08-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatroom_product_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='farmer_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
