# Generated by Django 5.2.1 on 2025-06-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ward_alter_profile_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='profile',
            name='tole',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Beni Municipality', editable=False, max_length=255),
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
