# Generated by Django 5.2.1 on 2025-09-04 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_role_customerprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='tole',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='tole',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='ward',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('customer', 'Customer'), ('admin', 'Admin')], default='admin', max_length=10)),
                ('address', models.CharField(default='Beni Municipality', editable=False, max_length=255)),
                ('phonenumber', models.CharField(max_length=20)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('tole', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
