# Generated by Django 5.2.1 on 2025-09-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_customerprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tole',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ward',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(default='Beni Municipality', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phonenumber',
            field=models.CharField(default=25, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='tole',
            field=models.CharField(default=' tdg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='address',
            field=models.CharField(default='Beni Municipality', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='phonenumber',
            field=models.CharField(default=88888, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='tole',
            field=models.CharField(default=8989, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
