# Generated by Django 5.2.1 on 2025-09-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_farmerreview_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerreview',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='accounts.customerprofile'),
        ),
        migrations.AlterField(
            model_name='farmerreview',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to='accounts.farmerprofile'),
        ),
    ]
