# Generated by Django 4.2.24 on 2025-10-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_farmerreview_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Blocked User',
                'verbose_name_plural': 'Blocked Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
    ]
