# Generated by Django 4.2.24 on 2025-11-20 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_merge_20251019_2144'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='farmerreport',
            name='user',
        ),
        migrations.AddField(
            model_name='customerreport',
            name='customer',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerreport',
            name='farmer',
            field=models.ForeignKey(default=8979, on_delete=django.db.models.deletion.CASCADE, to='accounts.farmerprofile'),
            preserve_default=False,
        ),
    ]
