# Generated by Django 5.2.1 on 2025-06-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_ward_remove_profile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('customer', 'Customer')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
