# Generated by Django 5.2.1 on 2025-06-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('customer', 'Customer'), ('admin', 'admin')], default='admin', max_length=10),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
