# Generated by Django 5.2.1 on 2025-08-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='last_name',
        ),
    ]
