# Generated by Django 5.2.1 on 2025-09-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_customerprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerreview',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
