# Generated by Django 5.2.1 on 2025-09-09 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_profile_address_remove_profile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerreview',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='accounts.customerprofile'),
        ),
        migrations.AlterField(
            model_name='farmerreview',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.farmerprofile'),
        ),
    ]
