# Generated by Django 4.2.24 on 2025-10-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_farmerreview_customer_and_more'),
        ('accounts', '0038_blockedprofile'),
    ]

    operations = [
    ]
