# Generated by Django 5.2.1 on 2025-07-04 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('तरकारी', 'तरकारी'), ('फलफुल', 'फलफुल'), ('खाद्यान्न', 'खाद्यान्न')], max_length=20)),
                ('sub_category', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('किलो', 'किलो'), ('क्विन्टल', 'क्विन्टल'), ('दर्जन', 'दर्जन'), ('मुरी', 'मुरी')], max_length=20)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
