# Generated by Django 5.2.1 on 2025-07-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category_roman',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
