# Generated by Django 5.2.1 on 2025-09-09 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_profile_address_remove_profile_latitude_and_more'),
        ('products', '0015_alter_product_options_alter_productsynonym_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmerprofile'),
        ),
    ]
