# Generated by Django 5.2.1 on 2025-08-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sub_category_roman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category_roman',
        ),
    ]
