# Generated by Django 5.2.1 on 2025-08-16 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_sub_category_roman'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('nepali', 'Nepali'), ('roman', 'Roman'), ('english', 'English')], max_length=10)),
                ('synonym', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
