# Generated by Django 5.2.1 on 2025-09-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customerprofile_address_customerprofile_latitude_and_more'),
        ('products', '0010_alter_product_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmerprofile'),
        ),
    ]
