# Generated by Django 5.2.1 on 2025-09-08 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_profile_address_remove_profile_latitude_and_more'),
        ('products', '0013_alter_product_farmer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productsynonym',
            options={'verbose_name': 'Product Synonym', 'verbose_name_plural': 'Product Synonyms'},
        ),
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.farmerprofile'),
        ),
        migrations.AlterField(
            model_name='productsynonym',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productsynonym',
            unique_together={('product', 'language', 'synonym')},
        ),
    ]
